### ISSUE TITLE
Sporadic error messages

### ISSUE THREAD

**Issue by jackfranklin** [Exafunction/codeium.nvim#239] opened 2024-10-05 14:14 UTC
I am running the latest commit of this plugin which did reduce the number of errors shown but I am still seeing them periodically:

```
[codeium/codeium.log] [ERROR 15:12:03] /home/jack/.local/share/nvim/lazy/codeium.nvim/lua/codeium/notify.lua:14: completion request failed:  {
[codeium/codeium.log]   code = 0,
[codeium/codeium.log]   out = '{"code":"unknown","message":"canceled: context canceled"}',
[codeium/codeium.log]   response = {
[codeium/codeium.log]     body = '{"code":"unknown","message":"canceled: context canceled"}',
[codeium/codeium.log]     exit = 0,
[codeium/codeium.log]     headers = { "Accept-Encoding: gzip", "Content-Type: application/json", "Vary: Origin", "Date: Sat, 05 Oct 2024 14:12:03 GMT", "Content-Length: 57",
"", "" },
[codeium/codeium.log]     status = 500
[codeium/codeium.log]   },
[codeium/codeium.log]   status = 500
[codeium/codeium.log] }
```

Would you consider providing a config setting to disable these messages, or at least make them not flash up on the screen? I don't understand why they happen, but they are very infrequently and not impacting my workflow so I would quite happily not see them.

**Comment by Juliuzzk** [comment] 2024-10-05 14:45
Same error here on the lattest commit

**Comment by pqn** [comment] 2024-10-05 18:54
This is a duplicate of #236, follow there for updates.

**Closed by pqn** 2024-10-05 18:54 UTC
