### ISSUE TITLE
With  commit #63835fc language_server_linux_x64 is not executable

### ISSUE THREAD

**Issue by catgoose** [Exafunction/codeium.nvim#85] opened 2023-08-31 23:54 UTC
`0664` permission bit is set so it is not executable

**Comment by pqn** [comment] 2023-10-05 18:25
Internally I don't think anything changed in our deployment scripts between the binary versions. Since we've updated beyond this specific binary, please feel free to comment again if the issue is still there, but I'll close this for now.

**Closed by pqn** 2023-10-05 18:25 UTC
