### ISSUE TITLE
1.2.64 not work

### ISSUE THREAD

**Issue by beingwww** [Exafunction/codeium.nvim#80] opened 2023-08-12 15:08 UTC
I'm using codeium.vim and your codeium.nvim at the same time, this is convenient for me, but when updating to your latest version, cmp doesn't seem to be able to show the relevant autocompletion anymore, and I'd like to know if there's a problem somewhere!

**Comment by beingwww** [comment] 2023-08-13 06:36
it seems to be the nvim-cmp's problem, I change nvim-cmp to some old version, and it worked now.

**Comment by brunolpsousa** [comment] 2023-08-13 15:56
> it seems to be the nvim-cmp's problem, I change nvim-cmp to some old version, and it worked now.

It looks like you're right. The problem seems to be commit [3b9f280](https://github.com/hrsh7th/nvim-cmp/commit/3b9f28061a67b19cadc13946de981426a6425e4a), the previous one is working fine for me

**Comment by chenhuiapp** [comment] 2023-08-21 20:59
How to use codeium now? Should I wait? Is there a work around?

**Comment by gaetan-puleo** [comment] 2023-08-27 09:10
> > it seems to be the nvim-cmp's problem, I change nvim-cmp to some old version, and it worked now.
> 
> Looks like you're right. The problem seems to be commit [3b9f280](https://github.com/hrsh7th/nvim-cmp/commit/3b9f28061a67b19cadc13946de981426a6425e4a), the previous one is working fine for me

I can confirm this information

**Comment by cleong14** [comment] 2023-08-31 20:39
#84 helped fix this issue for me.

**Comment by pqn** [comment] 2023-10-05 19:08
Closing given #84 and #88.

**Closed by pqn** 2023-10-05 19:08 UTC
