### ISSUE TITLE
Codeium throws errors on large files

### ISSUE THREAD

**Issue by wonderbeel** [Exafunction/codeium.nvim#20] opened 2023-02-09 09:56 UTC
Hi, I am playing around with this plugin and found an issue: I have treesitter configured to disable text highlight in big files (in those cases it is too slow and makes the editor hang for a couple of seconds after each key stroke, falling back to the regex parser solves this issue) and it seems that doing this makes your plugin break with the following error

```
Error detected while processing TextChangedI Autocommands for "*":
Error executing lua callback: .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:405: Failed to spawn process: {
  _additional_on_exit_callbacks = {},
  _shutdown_check = <userdata 1>,
  _stderr_results = {},
  _stdout_results = {},
  _user_on_exit = <function 1>,
  args = { "-sSL", "-D", "/tmp/plenary_curl_2fe047dc.headers", "--compressed", "-X", "POST", "-H", "Content-Type: application/json", "--data-raw", "{\"editor_options\": {\"insert_spaces\": true, \"tab_size\": 2}, \"metadata\": {\"extension_name\": \"vim\", \"ide_name\": \"neovim\", \"request_id\": 3, \"api_key\": \"API_KEY_HERE\", \"extension_version\": \"1.1.32\", \"ide_version\": \"0.8.3\"}, \"document\": {\"editor_language\": \"sql\", \"language\": 41, \"line_ending\": \"\\n\", \"cursor_offset\": 1043599, \"text\": \"ENTIRE_FILE_HERE\"}
```
(api key and text have been cropped out just to be safe)

If I enable treesitter highlight again the error disappear but then the editor became unusable, it would be great to fix this issue.

Let me know if you need something else to help debug this issue :).

**Comment by jcdickinson** [comment] 2023-03-01 04:29
I'm having trouble reproing this issue. How are you disabling TS? `TSBufDisable`?

**Comment by wonderbeel** [comment] 2023-03-01 08:38
I am disabling it directly in the configuration like this (basically what treesitter suggests in their docs https://github.com/nvim-treesitter/nvim-treesitter/blob/master/doc/nvim-treesitter.txt#L117 )
```
      highlight = {
        enable = true,
        disable = function(_, buf)
          local max_filesize = 100 * 1024 -- 100 KB
          local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(buf))
          if ok and stats and stats.size > max_filesize then
            return true
          end
        end,
      }
```

Now that I reread the issue again it was slightly misleading, what I am actually doing is disabling the `highlight` module and fallback to the regex, not disabling the entire treesitter, sorry my bad.

**Comment by jemag** [comment] 2023-04-01 02:42
Not sure if this is related, but also getting an error from the command window (`q:`), when editing text and completion is about to appear
```
Error detected while processing TextChangedI Autocommands for "*":
stack traceback:
	[C]: in function 'json_encode'
	...g/.local/share/nvim/lazy/codeium.nvim/lua/codeium/io.lua:407: in function 'post'
	.../.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:146: in function 'request'
	.../.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:287: in function 'request_completion'
	...ocal/share/nvim/lazy/codeium.nvim/lua/codeium/source.lua:103: in function 'complete'
	...jemag/.local/share/nvim/lazy/nvim-cmp/lua/cmp/source.lua:325: in function 'complete'
	...e/jemag/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:289: in function 'complete'
	...e/jemag/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:169: in function 'callback'
	...e/jemag/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:219: in function 'autoindent'
	...e/jemag/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:161: in function 'on_change'
	...e/jemag/.local/share/nvim/lazy/nvim-cmp/lua/cmp/init.lua:313: in function 'callback'
	...local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/autocmd.lua:49: in function 'emit'
	...local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/autocmd.lua:23: in function <...local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/autocmd.lua:22>
```

**Comment by brunolpsousa** [comment] 2023-06-09 15:03
I got the same error, but in my case the problem was not in the treesitter highlight, but in the big files themselves.

I was having this problem on a file with around 3500 lines and when I deleted around 1000 lines the problem was gone. On the other hand, I took a plain text file and copy/pasted until I got to about 5000 lines and the problem started.

I was also able to reproduce this in .zshrc and Lua files.

**Comment by waynebowie99** [comment] 2023-10-12 21:11
I'm getting this same error.

I think my issue is related to @brunolpsousa where I'm getting this on large C# files. 

Files that don't work:
- 34KB with ~ 700 lines
- 31KB with ~ 600 lines
- 28KB with ~ 680 lines

Working files
- 29KB with ~ 550 lines

It looks like the issue is tied more to the number of lines than anything in my case. Once the file gets to be around 600 lines it starts to fail in C#. 

I'm running on Windows. I can provide any logs as needed

**Comment by pqn** [comment] 2023-10-12 21:13
The fix is we probably have to switch the curl to accept data from stdin instead of passing it as an argument.

**Comment by amoschristian** [comment] 2024-04-24 13:40
Still happening in Apr 2024 :(

**Comment by mitya-murakhouski** [comment] 2024-05-02 07:37
> Still happening in Apr 2024 :(

Same thing for me. Getting this error at big yml files, than any completion call on any file raise this error

**Comment by Anthony-Fiddes** [comment] 2024-05-02 18:57
I was experiencing this issue too. I ended up configuring nvim-cmp per buffer, and excluding codeium on files over 100KB. From above comments, that number should probably be lower, but this works for me at the moment. You can see the change in my config [here](https://github.com/Anthony-Fiddes/kickstart.nvim/commit/8014d694c0435008240021bb5d7e864ccd492be9).

I referred to the nvim-cmp documentation on this page: https://github.com/hrsh7th/nvim-cmp/wiki/Advanced-techniques#disabling-completion-in-certain-contexts-such-as-comments

This obviously doesn't fix the root issue, and it would be nice if codeium worked in large files, but it will keep your neovim usable.

**Comment by brunolpsousa** [comment] 2024-05-03 19:01
I made a [PR](#184) to fix this. Can anyone test it and provide feedback?

**Comment by Anthony-Fiddes** [comment] 2024-05-03 19:18
Yup, I can confirm that it works. I just changed Exafunction to brunolpsousa in my config and reinstalled the plugin. Awesome stuff, hope it gets merged soon!

**Closed** 2024-05-03 19:41 UTC

**Comment by CNich** [comment] 2024-05-09 19:31
I'm getting this problem too. It doesn't seem to be for big files necessarily, but seems to come when I have many tabs open/leave neovim on for long periods of time. I switched to brunolpsousa and ran Lazy sync but still get this problem, am I doing something wrong?

**Comment by brunolpsousa** [comment] 2024-05-10 00:22
> I'm getting this problem too. It doesn't seem to be for big files necessarily, but seems to come when I have many tabs open/leave neovim on for long periods of time. I switched to brunolpsousa and ran Lazy sync but still get this problem, am I doing something wrong?

You don't need to use my branch because it has already been merged. Make sure your Lazy config is not locked to a specific commit or any other version control. If it still doesn't work, I think it would be better to open a new issue and provide logs.
